### ISSUE TITLE
Set public project to private

### ISSUE THREAD

**Issue by justinko** [cucumber-ltd/relish-gem#2]

**Comment by mattwynne** [comment]
So are we saying that projects will be private by default?

**Comment by mattwynne** [comment]
or are you talking about making a feature that allows me to switch a public project to private?

**Comment by justinko** [comment]
Yeah, I'm going to add `relish projects:status rspec-core:public`

**Comment by mattwynne** [comment]
or maybe:

relish projects:publicise foo/bar

status doesn't sound like a public/private thing to me.

It's nice to let people do this through the API, but surely this would be easier for us to do on the GUI? Less layers to maintain.

**Comment by justinko** [comment]
How about `relish projects:visibility` ?

**Comment by mattwynne** [comment]
yeah, nice.
