### ISSUE TITLE
You cannot add a collaborator to a project that belongs to an organization

### ISSUE THREAD

**Issue by justinko** [cucumber-ltd/relish-gem#3]
Even though the project's creator is an organization, you should still be able to add a collaborator who is not part of that organization.

**Comment by justinko** [comment]
Actually, the above is incorrect. It should work like this:

You can add a project collaborator on behalf of an organization if you have admin rights.

**Comment by mattwynne** [comment]
I've just deployed a fix that should allow you to do this.

**Comment by mattwynne** [comment]
Note that any member of the org can do it, whether or not they have admin rights. We're going to deprecate admin rights and make org membership a level playing field.
