### ISSUE TITLE
User email is set from invite email - even though they changed it on the sign up form

### ISSUE THREAD

**Issue by justinko** [cucumber-ltd/relish-gem#4]
Matt, I see that you're setting the email from the invite record. Got an email from a guy saying that he'd like to use a different email. Can you take care of this one?

**Comment by mattwynne** [comment]
The idea was to default the email on the form from the invite, but allow the user to submit the form with a different email if they wanted to.

I've got limited time on the net this week, but I'll take a look when I get a chance.

Why are these issues getting logged under the relish project as opposed to relishapp?

**Comment by justinko** [comment]
"Why are these issues getting logged under the relish project as opposed to relishapp?"

So users can come here and see that the issue has been noted.

**Comment by mattwynne** [comment]
just deployed a fix for this.
