### ISSUE TITLE
Relish 0.2.3 breaks generators when used with Devise

### ISSUE THREAD

**Issue by fortuity** [cucumber-ltd/relish-gem#7]
I'm using ruby 1.9.2p180, rubygems 1.7.2, Rails 3.0.6.

Wish I could tell you why this happens, but...

Try this with Relish 0.2.2 and you'll have no problem.

Try this with Relish 0.2.3 and Rails generators will fail.

`$ rails new testapp`

Gemfile:

<pre>
gem 'rails', '3.0.6'
gem 'devise', '1.3.0'
gem 'relish', '0.2.3'
</pre>

`$ bundle install`

`$ rails generate devise:install`

`$ rails generate devise user`

`$ rails generate controller foobar index`

Here's the full stack trace:

<pre>
/Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require': no such file to load -- jopenssl (LoadError)
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `block in require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/jruby-openssl-0.7.3/lib/openssl.rb:66:in `<top (required)>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `block in require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/bcrypt-ruby-2.1.4/lib/bcrypt.rb:6:in `<top (required)>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `block in require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/models/database_authenticatable.rb:2:in `<top (required)>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/models.rb:60:in `const_get'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/models.rb:60:in `block (2 levels) in devise'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/models.rb:59:in `each'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/models.rb:59:in `block in devise'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/models.rb:86:in `devise_modules_hook!'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/models.rb:58:in `devise'
        from /Users/danielkehoe/rails3/testapp/app/models/user.rb:4:in `<class:User>'
        from /Users/danielkehoe/rails3/testapp/app/models/user.rb:1:in `<top (required)>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:454:in `load'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:454:in `block in load_file'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:453:in `load_file'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:340:in `require_or_load'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:491:in `load_missing_constant'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:183:in `block in const_missing'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:181:in `each'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:181:in `const_missing'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/inflector/methods.rb:124:in `block in constantize'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/inflector/methods.rb:123:in `each'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/inflector/methods.rb:123:in `constantize'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:528:in `block in <class:Reference>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:538:in `yield'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:538:in `default'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:538:in `get'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/mapping.rb:79:in `to'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/rails/routes.rb:169:in `block in devise_for'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/rails/routes.rb:165:in `each'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/devise-1.3.0/lib/devise/rails/routes.rb:165:in `devise_for'
        from /Users/danielkehoe/rails3/testapp/config/routes.rb:2:in `block in <top (required)>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/actionpack-3.0.6/lib/action_dispatch/routing/route_set.rb:233:in `instance_exec'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/actionpack-3.0.6/lib/action_dispatch/routing/route_set.rb:233:in `draw'
        from /Users/danielkehoe/rails3/testapp/config/routes.rb:1:in `<top (required)>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:235:in `load'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:235:in `block in load'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:235:in `load'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application.rb:127:in `block in reload_routes!'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application.rb:127:in `each'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application.rb:127:in `reload_routes!'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application.rb:120:in `block in routes_reloader'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/file_update_checker.rb:32:in `call'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/file_update_checker.rb:32:in `execute_if_updated'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application/finisher.rb:51:in `block (2 levels) in <module:Finisher>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application/finisher.rb:52:in `call'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application/finisher.rb:52:in `block in <module:Finisher>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/initializable.rb:25:in `instance_exec'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/initializable.rb:25:in `run'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/initializable.rb:50:in `block in run_initializers'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/initializable.rb:49:in `each'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/initializable.rb:49:in `run_initializers'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application.rb:134:in `initialize!'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application.rb:77:in `method_missing'
        from /Users/danielkehoe/rails3/testapp/config/environment.rb:5:in `<top (required)>'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `block in require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/application.rb:103:in `require_environment!'
        from /Users/danielkehoe/.rvm/gems/ruby-1.9.2-p180@rails306/gems/railties-3.0.6/lib/rails/commands.rb:16:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
</pre>

**Comment by mattwynne** [comment]
Thanks for reporting this. Please use Relish 0.2.2 for the time being - the only difference in 0.2.3 is the support for JRuby / SSL connections which is what must have caused this regression.

**Comment by hakanensari** [comment]
I've sent over a [simple fix](https://github.com/mattwynne/relish/pull/8).

**Comment by mattwynne** [comment]
Please try installing version 0.3.0.pre of the relish gem and see if this fixes it for you.

**Comment by mattwynne** [comment]
I think this is fixed by 0.3.0, please comment in this ticket if that's wrong.

**Comment by fortuity** [comment]
Just confirming that the issue is resolved with version 0.3.0.

Tested with 

<pre>
gem 'rails', '3.0.7'
gem 'devise', '1.3.3'
gem 'relish', '0.3.0'
</pre>


and no problems.

**Comment by mattwynne** [comment]
Glad to hear it. Thanks for the feedback.
